# Generated by Django 3.2.6 on 2021-08-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
