# Generated by Django 3.2.6 on 2021-08-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='updated_date')),
            ],
        ),
    ]
